/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * labs-api
 * 
        This project provides a reference Python API built using FastAPI, the 
        aim of the project is:

        - To maintain a good know source of habits
        - Demonstrate how applications are meant to be put together at Anomaly
        - Democratize design of robust API    
    
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  UserResponse,
  GetUsersWithLimitsParams,
  UserRequest,
  GetUsersParams
} from '.././models'



  /**
 * @summary Query users between limits
 */
export const getUsersWithLimits = <TData = AxiosResponse<UserResponse[]>>(
    params?: GetUsersWithLimitsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Creates a new user based on
 * @summary Create a new user
 */
export const createUser = <TData = AxiosResponse<UserResponse>>(
    userRequest: UserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/users`,
      userRequest,options
    );
  }
/**
 * @summary Get all users
 */
export const getUsers = <TData = AxiosResponse<UserResponse[]>>(
    params?: GetUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users/infinite`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get a user by their id
 * @summary Get a particular user
 */
export const getUserById = <TData = AxiosResponse<UserResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users/${id}`,options
    );
  }
/**
 * Delete a user from the database

The endpoint will look to see if the user exists, and if so
will attempt to delete the user from the database and
return a 204 response. If the user does not exist, a 404
 * @summary Delete a particular user
 */
export const deleteUser = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/users/${id}`,options
    );
  }
/**
 * @summary Update a particular user
 */
export const updateUser = <TData = AxiosResponse<unknown>>(
    id: string,
    userRequest: UserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/users/${id}`,
      userRequest,options
    );
  }
export type GetUsersWithLimitsResult = AxiosResponse<UserResponse[]>
export type CreateUserResult = AxiosResponse<UserResponse>
export type GetUsersResult = AxiosResponse<UserResponse[]>
export type GetUserByIdResult = AxiosResponse<UserResponse>
export type DeleteUserResult = AxiosResponse<void>
export type UpdateUserResult = AxiosResponse<unknown>
